[en]
contentDir = "content/english"
copyright = "Designed By Kaster Technologies."
footer_content = "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore dolore magna aliquyam eratnonumy onsetetur"
languageCode = "en-us"
languageName = "En"
weight = 1
[fr]
contentDir = "content/french"
copyright = "Designed By [Themefisher](https://themefisher.com/) & Developed By [Gethugothemes](https://gethugothemes.com/)"
footer_content = "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore dolore magna aliquyam eratnonumy onsetetur"
languageCode = "fr-fr"
languageName = "Fr"
weight = 2
