[en]
contentDir = "content/english"
copyright = "Designed By Kaster Technologies."
footer_content = "Our company believes that every production planner should be empowered to do more and set new productivity standards. It is our mission to make this a possibility at a fraction of the cost and to ensure AI can be put to good use, in increasing the global production volume of medication and vaccine manufacturing."
languageCode = "en-us"
languageName = "En"
weight = 1
[fr]
contentDir = "content/french"
copyright = "Designed By [Themefisher](https://themefisher.com/) & Developed By [Gethugothemes](https://gethugothemes.com/)"
footer_content = "Notre société croît que chaque planificateur de production devrait être habilité à faire plus et à établir de nouvelles normes de productivité. Notre mission est de rendre cela possible à une fraction du coût et de veiller à ce que l'IA puisse être utilisée à bon escient, en augmentant le volume de production mondial de médicaments et de vaccins."
languageCode = "fr-fr"
languageName = "Fr"
weight = 2
