[[footer]]
name = "Faq"
url = "faq/"
weight = 1
[[footer]]
name = "Termes & Conditions"
url = "terms-conditions/"
weight = 2
[[footer]]
name = "Politique de confidentialité"
url = "privacy-policy/"
weight = 3
[[main]]
name = "Accueil"
url = ""
weight = 1
[[main]]
name = "À Propos"
url = "about/"
weight = 2
[[main]]
name = "Équipe"
url = "team/"
weight = 4
[[main]]
name = "Contactez-nous"
url = "contact/"
weight = 6
