[[footer]]
name = "Faq"
url = "faq/"
weight = 1
[[footer]]
name = "Terms & Conditions"
url = "terms-conditions/"
weight = 2
[[footer]]
name = "Privacy Policy"
url = "privacy-policy/"
weight = 3
[[main]]
name = "Home"
url = ""
weight = 1
[[main]]
name = "About"
url = "about/"
weight = 2
[[main]]
name = "Team"
url = "team/"
weight = 4
[[main]]
name = "Contact"
url = "contact/"
weight = 6
[[main]]
name = "Career"
parent = "Pages"
url = "career/"
[[main]]
name = "How It Works"
parent = "Pages"
url = "how-it-works/"
