apple_touch_icon = "images/favicon.png"
author = "Themefisher"
contact_form_action = "#"
custom_script = ""
description = "Kaster Technologies"
favicon = "images/favicon.png"
favicon_16x16 = "images/favicon.png"
favicon_32x32 = "images/favicon.png"
image = "images/logo.png"
logo = "images/logo.JPG"
logo_text = "Kaster Technologies"
logo_width = ""
[cookies]
button = "I Accept"
content = "This site uses cookies. By continuing to use this website, you agree to their use."
enable = false
expire_days = 2
[footer_call_to_action]
enable = true
title = "Join 75,000+ growing business That **Use Copper To Their Brand**"
[footer_cta_button]
enable = true
label = "Get Started With Us"
link = "contact"
[navigation_button_bordered]
enable = true
label = "Sign Up"
link = ""
[navigation_button_linked]
enable = false
label = "Log In"
link = ""
[preloader]
enable = false
greetings = "Kaster"
greetings_to = ""
preloader = "images/preloader.png"
[subscription]
enable = true
mailchimp_form_action = "https://gmail.us4.list-manage.com/subscribe/post?u=463ee871f45d2d93748e77cad&amp;id=a0a2c6d074"
mailchimp_form_name = "b_463ee871f45d2d93748e77cad_a0a2c6d074"
[[social]]
icon = "fab fa-facebook"
link = "#"
title = "facebook"
[[social]]
icon = "fab fa-github"
link = "#"
title = "github"
[[social]]
icon = "fab fa-linkedin"
link = "#"
title = "linkedin"
